# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='artist',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='copyright',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='identifier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='publisher',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='pubyear',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
