# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='collectible',
            name='copyright',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
