# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20170626_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link',
        ),
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.URLField(default='http://www.google.com'),
            preserve_default=False,
        ),
    ]
