# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20170627_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
