# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobby',
        ),
    ]
